### PR TITLE
Mgv7p hell development

### PR DESCRIPTION
**Pull request by paramat**
Ready for testing.
Teleport to y = -1000 to find hell.
You will need to travel around to find a hell dungeon.

Hell is approximately between y = -768 and y = -1010.
Hell mapchunks take on average 50ms to generate, roughly the same as surface mapchunks. I have temporarily left in the timetaker so you can see mapchunk generation times.

Hell needs to be deep to avoid players at surface level generating hell mapchunks, and players at the top of hell generating surface mapchunks, this would make mapgen unnecessarily more intensive. So it is best to have a large separation between surface and hell.

Lava 'waterfalls' are rare because they cause a huge amount of lava spreading.
If you find one and wait 15 mins you can see how much it spreads.
I suggest that lava has it's 'liquid_range' reduced, to reduce how much it spreads? Then lava can be made more common.

### CODE REVIEW

**Comment by paramat** [comment]
The reason the dungeons are often floating in air is because the dungeon generation option is: dungeons generate in solid nodes only, or, dungeons generate anywhere.
Having the dungeons appear outside solid nodes looks better to me and more like Minecraft's nether fortresses, which seem to be often exposed.

There are many ways i can alter the dungeons if you want them to be different in some way.
These are the things i can alter:

Min and max Y for dungeon generation.
Generation in solid nodes only (like normal Multicraft dungeons) or generation anywhere.
Corridor min and max length.
Min and max number of rooms.
Distribution created by perlin noise and rarity.
Node used for walls.
Whether diagonal corridors are generated.
Corridor width and height.
Min and max length, width, height of rooms.
Min and max length, width, height of the first room generated.

**Comment by paramat** [comment]
@MoNTE48 this PR now has an unrelated commit added, is there a reason for that?

**Comment by paramat** [comment]
Actually, i may have added this commit myself by mistake. I'll try to remove it myself.

**Comment by paramat** [comment]
I'm unable to remove that commit, can anyone else?

**Comment by paramat** [comment]
Due to #131 i am currently unable to continue work on the hell dimension, as i will be unable to solve the conflicts.

**Comment by paramat** [comment]
Here's what i suggest:
The hell dimension is roughly finished, i suggest we merge it as soon as possible to not lose this work, then i can continue work later.
If we agree to do this i will try to fix the conflicts to make it mergeable.

**Comment by paramat** [comment]
This PR is complete, but i am happy to change anything.
However this PR does not include any way for players to travel to and from hell, that is best added as a mod in the subgame. The 'nether' mod by PilzAdam, sofar and myself has portal code, but will need some alteration to work with the MultiCraft hell.

**Comment by paramat** [comment]
@MoNTE48 why was this closed?

I deleted my fork so this PR cannot be reopened.
But, i can make make a new PR with these changes if you are still interested in merging this.

**Comment by MoNTE48** [comment]
This is still WIP and costs too much.  I think mv will come back to this in the future.

**Comment by paramat** [comment]
It's not WIP.
Travel to and from hell needs to be a game mod, that should be a separate PR.
What do you mean by 'costs too much'? There's nothing about it which is intensive.

**Comment by MoNTE48** [comment]
Well, we don't have high resolution textures, mod for traveling to hell, special mobs that will be in hell.  Not thought out a lot of things.
I am sure that this will be added to MultiCraft in the coming 2-3 months. But now I would like to fix some of the problems.
I will appreciate if you check email



понедельник, 20 мая 2019 г., 21:25 +0200 от notifications@github.com  <notifications@github.com>:

**Comment by paramat** [comment]
Ok, let me know if or when you want this PR remade.

**Comment by paramat** [comment]
You're welcome to recreate this PR and merge it if you want. Here's how to do that:

* Create a new branch.
* In terminal, navigate to your local repository and use:
`wget https://github.com/MultiCraftProject/MultiCraft/pull/130.patch`
The patch will appear in the repository.
* Open the patch in a text editor and delete all the changes to the 'default' game, because these changes will not apply due to the game having changed so much. Only the changes to mapgen_v7p.cpp and mapgen_v7p.h should remain.
* In terminal use:
`git am 130.patch`
to apply the patch changes to the branch.
* Delete the patch file.

The additional changes needed to the 'default' game are contained in the original patch file and are:
```
diff --git a/games/default/files/default/crafting.lua b/games/default/files/default/crafting.lua
index c21181f01..c0ba96b08 100644
--- a/games/default/files/default/crafting.lua
+++ b/games/default/files/default/crafting.lua
@@ -434,6 +434,14 @@ minetest.register_craft({
     }
 })
 
+minetest.register_craft({
+    output = 'default:hellstone_brick',
+    recipe = {
+        {'default:hellstone', 'default:hellstone'},
+        {'default:hellstone', 'default:hellstone'},
+    }
+})
+
 minetest.register_craft({
     type = "shapeless",
     output = "default:gunpowder",
diff --git a/games/default/files/default/mapgen.lua b/games/default/files/default/mapgen.lua
index 47a6610ff..b93dd6986 100644
--- a/games/default/files/default/mapgen.lua
+++ b/games/default/files/default/mapgen.lua
@@ -37,6 +37,7 @@ minetest.register_alias("mapgen_stair_cobble", "stairs:stair_cobble")
 minetest.register_alias("mapgen_mossycobble", "default:mossycobble")
 minetest.register_alias("mapgen_sandstonebrick", "default:sandstone")
 minetest.register_alias("mapgen_stair_sandstonebrick", "stairs:stair_sandstone")
+minetest.register_alias("mapgen_hellstone_brick", "default:hellstone_brick")
 
 
 --
@@ -357,6 +358,45 @@ function default.register_ores()
 	    y_min          = -59,
 	    y_max          = -0,
 	})
+
+	-- Hell glowstone
+
+	minetest.register_ore({
+	    ore_type       = "scatter",
+	    ore            = "default:glowstone",
+	    wherein        = "default:hellstone",
+	    clust_scarcity = 7 * 7 * 7,
+	    clust_num_ores = 4,
+	    clust_size     = 2,
+	    y_min          = -31000,
+	    y_max          = -113,
+	})
+
+	-- Hell quartz ore
+
+	minetest.register_ore({
+	    ore_type       = "scatter",
+	    ore            = "default:quartz_ore",
+	    wherein        = "default:hellstone",
+	    clust_scarcity = 16 * 16 * 16,
+	    clust_num_ores = 8,
+	    clust_size     = 3,
+	    y_min          = -31000,
+	    y_max          = -113,
+	})
+
+	-- Hell lava sources
+
+	minetest.register_ore({
+	    ore_type       = "scatter",
+	    ore            = "default:lava_source",
+	    wherein        = "default:hellstone",
+	    clust_scarcity = 48 * 48 * 48,
+	    clust_num_ores = 1,
+	    clust_size     = 1,
+	    y_min          = -31000,
+	    y_max          = -113,
+	})
 end
 
 
@@ -869,16 +909,16 @@ function default.register_biomes()
 		humidity_point = 80,
 	})
 
-	-- Underground
+	-- Hell
 
 	minetest.register_biome({
-		name = "underground",
+		name = "hell",
 		--node_dust = "",
 		--node_top = "",
 		--depth_top = ,
 		--node_filler = "",
 		--depth_filler = ,
-		--node_stone = "",
+		node_stone = "default:hellstone",
 		--node_water_top = "",
 		--depth_water_top = ,
 		--node_water = "",
diff --git a/games/default/files/default/nodes.lua b/games/default/files/default/nodes.lua
index c5c09ce05..2cd47aaf1 100644
--- a/games/default/files/default/nodes.lua
+++ b/games/default/files/default/nodes.lua
@@ -618,9 +618,9 @@ minetest.register_node("default:reeds", {
 
 minetest.register_node("default:quartz_ore", {
     description = "Quartz Ore",
-    tiles = {"default_quartz_ore.png"},
+    tiles = {"default_hellstone.png^default_quartz_ore.png"},
     groups = {cracky=3, stone=1, building = 1},
-    drop = 'default:quartz_crystal',
+    drop = "default:quartz_crystal",
     sounds = default.node_sound_stone_defaults(),
 })
 

@@ -1681,3 +1664,40 @@ minetest.register_node("default:snowblock", {
     }),
     drop = "default:snow 4",
 })
+
+
+--
+-- Hell nodes
+--
+
+minetest.register_node("default:hellstone", {
+    description = "Hellstone",
+    tiles = {"default_hellstone.png"},
+    groups = {cracky = 3, stone = 1, building = 1, decorative = 1},
+    sounds = default.node_sound_stone_defaults(),
+})
+
+minetest.register_node("default:hellstone_brick", {
+    description = "Hellstone Brick",
+    tiles = {"default_hellstone_brick.png"},
+    groups = {cracky = 3, stone = 1, building = 1, decorative = 1},
+    sounds = default.node_sound_stone_defaults(),
+})
```
You'll need to add these 2 new textures:
default_hellstone.png
default_hellstone_brick.png

And this texture needs changing to be quartz ore on a transparent background:
default_quartz_ore.png

I was going to recreate this PR myself, but after reading your forum post on Saturday where you threatened to visit me and 'put me in hospital', and suggested i commit suicide, i will leave it to you and your team and will have zero involvement with MultiCraft from now on.

**Pull request closed without merging**
