### PR TITLE
Fix compilation of sync branch on Linux

### LINKED ISSUE #138: Can't compile sync branch on Linux
I reforked MultiCraft but compilation fails on 'sync' branch:
(the 'server' branch does not exist in my fork for some reason).
```
/MultiCraft/src/client.cpp: In member function
‘void Client::initLocalMapSaving(const Address&, const string&, bool)’:
/MultiCraft/src/client.cpp:782:18: error: expected type-specifier before ‘MapDatabaseSQLite3’
  m_localdb = new MapDatabaseSQLite3(world_path);
```
I suspect https://github.com/MultiCraftProject/MultiCraft/commit/a13e033c89c15692c56859756c1c6e9f78623670 may be the problem as it un-commented this section.
See https://github.com/MultiCraftProject/MultiCraft/commit/8a4933f707d121211b3507a7d7fb4c27ab0eb2b9 "Completely disable SQLite so it can be omitted" which commented this section.

### PR DESCRIPTION
**Pull request by paramat**
Fixes #138

### CODE REVIEW

**Comment by paramat** [comment]
Just seen you did this in the server branch in https://github.com/MultiCraftProject/MultiCraft/commit/6dcc8a9f80beb67f7b494b942d385d627d2af279#diff-34f48ad91ac6c202ac60b0348ae90e30

**Comment by paramat** [comment]
Hmmm i guess you want me to work on the 'server' branch? In which case, how do i get that branch in my fork? It doesn't exist in my fork of MultiCraft.

**Comment by MoNTE48** [comment]
I'm not a Github specialist, I'm sorry.  I do not know why you do not have server branch.  The sync branch is obsolete, I will delete it soon.

**Comment by paramat** [comment]
No problem, i can re-fork the master branch now.

**Pull request closed without merging**
