### PR TITLE
Show item description over hudbar

### PR DESCRIPTION
**Pull request by kilbith**
screenshot_20190520_162834

### CODE REVIEW

**Comment by MoNTE48** [comment]
Looks great. But can it be added in builtin?

**Comment by kilbith** [comment]
> Looks great. But can it be added in builtin?
Done.

**Comment by MoNTE48** [comment]
Rebase and squash is a dangerous thing. I'll add it manually

**Comment by MoNTE48** [comment]
Could you make this text disappear in 3 seconds?

**Comment by kilbith** [comment]
> Could you make this text disappear in 3 seconds?

Set this variable to `3` : https://github.com/MultiCraftProject/MultiCraft/blob/server/builtin/game/misc.lua#L234

**Pull request closed without merging**
