### PR TITLE
Completely disable SQLite so it can be omitted

### PR DESCRIPTION
**Pull request by sfan5**

### CODE REVIEW

**Comment by sfan5** [comment]
Not sure, the code can be removed of course.

**Comment by MoNTE48** [comment]
@sfan5 excellent. Then I wait for it and I do merge

**Comment by MoNTE48** [comment]
What happens if someone starts old sqlite3 world?
We must avoid crash and simply tell the player that his world is very old

**Comment by sfan5** [comment]
I think it prints an error message in chat.

**Comment by MoNTE48** [comment]
@sfan5 this is bad idea - player can't see chat before they get into the game.
You could put the error information in a window with an error that appears if there is an error in the lua code when loading the world, for example.

**Pull request merged**
