### PR TITLE
iOS: use MetalANGLE backend

### PR DESCRIPTION
**Pull request by MoNTE48**

### CODE REVIEW

**Comment by githubXREALM** [comment]
Its awseome seeing the game get REALLY GOOD!

**Comment by MoNTE48** [comment]
@XREALM-MultiCraft Do you understand why this is needed and what changes it will make?

**Comment by XREALM-MultiCraft** [comment]
> @XREALM-MultiCraft Do you understand why this is needed and what changes it will make?

Yes! :) 👍.thank you @MoNTE48 pls continue it! The game is going well.! EVERYTHING IS THANKS TO YOU AND YOUR TEAM! Us multicrafters love you all! i wont spam much i only bug report and stuff 1 time a month to not spam you..and one last thing goooooood luck coding and stuff you are a pro :) ok See you whenever we talk again

**Comment by XREALM-MultiCraft** [comment]
@MoNTE48 /settings" right?

**Comment by MoNTE48** [comment]
> /settings" right?
 No. Using a newer graphical backend. It will not be noticeable for ordinary players in any way.

**Comment by XREALM-MultiCraft** [comment]
> > /settings" right?
>  No. Using a newer graphical backend. It will not be noticeable for ordinary players in any way.

You can make the text in /settings black and background white :) to make it more noticeable

**Comment by OwOBot27** [comment]
??

**Pull request closed without merging**
